# -*- coding: utf-8 -*-
"""Practice ANN on Colab - Predicting possibility of having heart attack

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15imXGB3MjA1NiE2xy0x0JA16P5Mj5GXl

#Importing libraries
"""

import numpy as np
import pandas as pd
import tensorflow as tf

tf.__version__

"""#Connecting Colab to Gdrive"""

from google.colab import drive
drive.mount('/content/gdrive')

"""#Importing dataset         

*   There are 14 columns, and count first column as 0.  I need column 0-13 for x
*   The 14th column (the last column) shows the outcome of whether a patient will have hurt attack or not
"""

dataset = pd.read_csv('/content/gdrive/My Drive/heart.csv')
x = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, -1].values

"""#Print(x) and (y) to see if datasets were read correctly"""

print(x)

print(y)

"""#Splitting the dataset into the training set and test set"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

"""#Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

"""#Initializing ann"""

ann = tf.keras.models.Sequential()

"""#Input layer and the first hidden layer (units is random, so picked 6)"""

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

"""#Additional second hidden layer (unit is 1 because the outcome is only either 0 or 1)"""

ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

"""#Compiling the ANN"""

ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

"""#Training ANN on the Training set (size 32 is default) (accuracy 0.88 not bad)"""

ann.fit(x_train,y_train,batch_size=32,epochs=100)

"""# Predict - a person with following charactristics will have heart attack or not.  0 = no/less chance of heart attack OR  1 = more chance of heart attack

* 1) age=50
* 2) sex=1 (male)
* 3) chest pain type (4 values)=1
* 4) resting blood pressure=172
* 5) serum cholestoral in mg/dl=221
* 6)fasting blood sugar > 120 mg/dl=1
* 7) resting electrocardiographic results (values 0,1,2)=0
* 8) maximum heart rate achieved=160
* 9) exercise induced angina=0
* 10) oldpeak = ST depression induced by exercise relative to rest=1.5
* 11)the slope of the peak exercise ST segment=1
* 12) number of major vessels (0-3) colored by flourosopy=3
* 13) thal: 0 = normal; 1 = fixed defect; 2 = reversable defect=2

#Probablity of if this patient will get the heart attack is less likely becuase the number I got is 0.04 which is close to zero.
"""

print(ann.predict(sc.transform([[50,1,1,172,221,1,0,160,0,1.5,1,3,2]])))

"""#Could also print in True or False by adding 0.5"""

print(ann.predict(sc.transform([[50,1,1,172,221,1,0,160,0,1.5,1,3,2]]))>0.5)